PORTNAME=	gershwin-dbuskit
DISTVERSION=	20250710
CATEGORIES=	devel gnustep

MAINTAINER=	jpm820@proton.me
COMMENT=	DBusKit framework for Gershwin
WWW=		https://github.com/gershwin-desktop/gershwin-dbuskit

LICENSE=	GPLv2+

USES=		gershwin
USE_GERSHWIN=	back build

USE_GITHUB=	yes
GH_ACCOUNT=	gershwin-desktop
GH_TAGNAME=	5f69f33

.include <bsd.port.mk>
